# Generated by Django 4.0 on 2021-12-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_product', '0002_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacture_date',
            field=models.DateField(),
        ),
    ]
