# Generated by Django 4.0 on 2021-12-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_product', '0003_alter_product_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='sub_category',
        ),
    ]
